server:
  port: 8080

spring:
  application:
    name: jpa-with-inheritance
  datasource:
    url: jdbc:h2:mem:test
    username: SA
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true

logging:
  pattern:
  level:
    org.hibernate.orm.jdbc.bind: trace
