version: '3.8'
services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    environment:
      - MYSQL_DATABASE=employee
      - MYSQL_ROOT_PASSWORD=secret@123
    ports:
      - "3300:3306"
    restart: always
    networks:
      - internal-net
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
  backend:
    build:
      context: .
    environment:
      NODE_ENV: dev
    depends_on:
      mysql-server:
        condition: service_healthy
    networks:
      - internal-net
    ports:
      - 8080:8080
networks:
  internal-net:
    driver: bridge