services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3300:3306
    networks:
      - internal-net
    environment:
      MYSQL_DATABASE: employee
      MYSQL_USER: emp1
      MYSQL_PASSWORD: secret@123
      MYSQL_ROOT_PASSWORD: secret@123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
    build:
      context: .
    environment:
      NODE_ENV: dev
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - internal-net
    ports:
      - 8080:8080
networks:
  internal-net:
    driver: bridge


#services:
#  mysqldb:
#    image: "mysql:8.0"
#    restart: always
#    ports:
#      - 3300:3306
#    networks:
#      - internal-net
#    environment:
#      MYSQL_DATABASE: employee
#      MYSQL_USER: root
#      MYSQL_PASSWORD: secret@123
#      MYSQL_ROOT_PASSWORD: secret@123
#  backend:
#    build:
#      context: ./
#    environment:
#      NODE_ENV: dev
#    depends_on:
#      mysqldb:
#        condition: service_healthy
#    networks:
#      - internal-net
#    ports:
#      - 8080:8080
#networks:
#  internal-net:
#    driver: bridge