server:
  port: 8200

spring:
  application:
    name: consumer application
  datasource:
    url: jdbc:h2:mem:consumer_db
    username: SA
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093, localhost:9094
    template:
      default-topic: orders-placed
    consumer:
      group-id: order-consumer-group
      enable-auto-commit: true

logging:
  pattern:
  level:
    org.hibernate.orm.jdbc.bind: trace




