server:
  port: 8100

spring:
  application:
    name: Pagination-demo
  datasource:
    url: jdbc:h2:mem:orderdb
    username: SA
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
  data:
    web:
      pageable:
        default-page-size: 4

logging:
  pattern:
  level:
    org.hibernate.orm.jdbc.bind: trace


